#!/bin/sh
mkdir -p $HOME/Library/Developer/Xcode/UserData/FontAndColorThemes
cp ./Solarized\ Dark.dvtcolortheme $HOME/Library/Developer/Xcode/UserData/FontAndColorThemes
cp ./Solarized\ Light.dvtcolortheme $HOME/Library/Developer/Xcode/UserData/FontAndColorThemes
